name: 'AWS CDK GitHub Actions'
description: 'Runs AWS-CDK via GitHub Actions.'
author: 'poad <ken-yo@mbr.nifty.com>'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  cdk_stack:
    description: 'AWS CDK stack name to execute.'
    default: '*'
  cdk_subcommand:
    description: 'AWS CDK subcommand to execute.'
    required: true
  working_dir:
    description: 'AWS CDK working directory.'
    default: './'
  actions_comment:
    description: 'Whether or not to comment on pull requests.'
    default: true
runs:
  using: 'docker'
  image: './Dockerfile'
